### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by qiming111** [Perception-and-Neurodynamics-Laboratory/Matlab-toolbox-for-DNN-based-speech-separation#2]
There were some errors in the files when I was excuting the programs.In the 'run_erery.m' file,it reported that there was no test_data.I found it generated test_factory_mix_aft2.mat and train_factory_mix_bef2.mat files.But I don't know how to use them.

**Comment by Peidong-Wang** [comment]
Can you post your RUN.m, load_config.m, and the exact error message? I think this may relate to the file paths.

**Comment by pnl-cse-osu** [comment]
closed due to lack of activity
